name: giga_mario_bench
channels:
  - conda-forge
dependencies:
  - python=3.12
  - setuptools
  - pytest
  - pytest-cov
  - numpy
  - pandas
  - altair
  - hydra-core
  - omegaconf
  - matplotlib
  - pip
  - pip:
      - -e .
      - cnsplots>=0.5.0
      - vl-convert-python>=1.0
variables:
  PYTHONPATH: src
