"""Write start-to-end Python cells and a Nextflow workflow input list."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from giga_mario_bench.bench.build import BENCHES, DEFAULT_SPEC, param_slug
from giga_mario_bench.giga_mario import repo_root
from giga_mario_bench.models.general import MODELS, model_params_slug

# Homology splits need MARKED/FNA that this toy panel does not carry.
# ``random`` is the method Giga_Mario can assign from an ID list alone.
GRID_SPLITS = ("random",)


def _load_spec(path: Path | None, data_out, model_out, score_out) -> dict[str, Any]:
    if path is None:
        if not data_out or not model_out or not score_out:
            raise ValueError(
                "score prepare needs --data-out, --model-out, and --score-out, "
                "or a JSON file with those keys"
            )
        return {
            "data_out": str(data_out),
            "model_out": str(model_out),
            "score_out": str(score_out),
        }
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    for key in ("data_out", "model_out", "score_out"):
        if key not in payload:
            raise ValueError(f"spec JSON missing {key}")
    return payload


def prepare_grid(
    *,
    data_out: Path | None = None,
    model_out: Path | None = None,
    score_out: Path | None = None,
    spec_json: Path | None = None,
    all_cells: bool = False,
    bench: str | None = None,
    split: str | None = None,
    model: str | None = None,
    spec: dict[str, Any] | None = None,
    exec_root: Path | None = None,
    max_epochs: int = 20,
    patience: int = 5,
) -> list[Path]:
    """Write one runnable script per selected grid cell.

    ``--all`` crosses registered benchmarks, the default parameter set,
    grid splits, and registered models. Paths are required either as flags
    or inside ``spec_json``.
    """
    loaded = _load_spec(spec_json, data_out, model_out, score_out)
    panel = dict(DEFAULT_SPEC)
    if spec:
        panel.update(spec)
    if "benches" in loaded:
        benches = list(loaded["benches"])
    elif all_cells or bench is None:
        benches = list(BENCHES)
    else:
        benches = [bench]
    if "splits" in loaded:
        splits = list(loaded["splits"])
    elif all_cells or split is None:
        splits = list(GRID_SPLITS)
    else:
        splits = [split]
    if "models" in loaded:
        models = list(loaded["models"])
    elif all_cells or model is None:
        models = sorted(MODELS)
    else:
        models = [model]
    root = repo_root()
    scripts_root = Path(exec_root) if exec_root else root / "src" / "giga_mario_bench" / "exec"
    written: list[Path] = []
    slug = param_slug(panel)
    for bench_name in benches:
        for split_name in splits:
            for model_name in models:
                model_slug = model_params_slug(model_name)
                script = (
                    scripts_root
                    / bench_name
                    / slug
                    / split_name
                    / f"{model_name}_{model_slug}.py"
                )
                script.parent.mkdir(parents=True, exist_ok=True)
                script.write_text(
                    _script_text(
                        bench=bench_name,
                        panel=panel,
                        split=split_name,
                        model=model_name,
                        data_out=loaded["data_out"],
                        model_out=loaded["model_out"],
                        score_out=loaded["score_out"],
                        max_epochs=int(loaded.get("max_epochs", max_epochs)),
                        patience=int(loaded.get("patience", patience)),
                    ),
                    encoding="utf-8",
                )
                script.chmod(0o755)
                written.append(script)
                print(f"prepared exec script: {script}")
    manifest = scripts_root / "manifest.json"
    manifest.write_text(
        json.dumps([str(path) for path in written], indent=2) + "\n",
        encoding="utf-8",
    )
    return written


def _script_text(**kwargs: Any) -> str:
    blob = json.dumps(kwargs, indent=2, sort_keys=True)
    return f'''#!/usr/bin/env python3
"""Start-to-end cell generated by ``giga_mario_bench score prepare``.

This file is meant to run on its own. It reuses artifacts that already exist.
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve()
for _parent in _HERE.parents:
    if (_parent / "VERSION").is_file() and (_parent / "src" / "giga_mario_bench").is_dir():
        _src = _parent / "src"
        if str(_src) not in sys.path:
            sys.path.insert(0, str(_src))
        break
else:
    raise SystemExit("Cannot find the giga_mario_bench repository root")

from giga_mario_bench.pipeline import run_cell  # noqa: E402

CELL = {blob}


def main() -> int:
    """Run this cell and print the score summary."""
    import json

    result = run_cell(
        bench=CELL["bench"],
        spec=CELL["panel"],
        split=CELL["split"],
        model=CELL["model"],
        data_out=Path(CELL["data_out"]),
        model_out=Path(CELL["model_out"]),
        score_out=Path(CELL["score_out"]),
        max_epochs=CELL["max_epochs"],
        patience=CELL["patience"],
    )
    print(json.dumps({{k: result[k] for k in ("status", "f1", "r2", "rocauc")}}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
